FROM node:20-alpine

WORKDIR /usr/src/app

COPY . .

RUN apt-get update && \
    apt-get install -y zip libjpeg-turbo-progs nasm && \
    rm -rf /var/lib/apt/lists/*

RUN npm install --force && npm run build

RUN zip -r dist.zip dist

CMD ["true"]

